version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    restart: always
    command:
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--providers.docker=true"
      # Only expose container that have traefik.enable=true
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Use http challenge for certificate
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.email=[EMAIL]"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      # Use this for debugging purposes only 
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/home/k8s/docker/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    container_name: "gitlab"
    restart: always
    extra_hosts:
      - "id.universphere.cloud:[INTERNAL-IP]"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitlab.rule=Host(`git.universphere.cloud`)"
      - "traefik.http.routers.gitlab.entrypoints=websecure"
      - "traefik.http.routers.gitlab.tls.certresolver=myresolver"
      - "traefik.http.routers.gitlab.tls=true"
      - "traefik.http.services.gitlab.loadbalancer.server.port=80"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.universphere.cloud'
        
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        #nginx['enable'] = false
        
        #gitlab_rails['gitlab_signin_enabled'] = false
        

        # OIDC
        gitlab_rails['omniauth_providers'] = [
                {
                  name: "openid_connect",
                  label: "Keycloak",
                  args: {
                    name: "openid_connect",
                    scope: ["openid", "profile", "email"],
                    response_type: "code",
                    issuer: "https://id.universphere.cloud/realms/master",
                    client_auth_method: "query",
                    discovery: true,
                    uid_field: "preferred_username",
                    pkce: true,
                    client_options: {
                      identifier: "[CLIENT_ID]",
                      secret: "[SECRET]",
                      redirect_uri: "https://git.universphere.cloud/users/auth/openid_connect/callback",
                      gitlab: {
                        groups_attribute: "groups",
                        required_groups: ["Developer"]
                      }
                    }
                  }
                }
              ]
        gitlab_rails['omniauth_allow_single_sign_on'] = ['openid_connect']
        gitlab_rails['omniauth_block_auto_created_users'] = false
    volumes:
      - /home/k8s/docker/gitlab/config:/etc/gitlab
      - /home/k8s/docker/gitlab/logs:/var/log/gitlab
      - /home/k8s/docker/gitlab/data:/var/opt/gitlab  

  postgres:
      image: postgres
      container_name: "keycloak-db"
      volumes:
        - /home/k8s/docker/keycloak/pg_data:/var/lib/postgresql/data
      environment:
        POSTGRES_DB: keycloak
        POSTGRES_USER: keycloak
        POSTGRES_PASSWORD: password
  
  keycloak:
      image: quay.io/keycloak/keycloak
      container_name: "keycloak"
      command: "start-dev"
      environment:
        KC_PROXY_ADDRESS_FORWARDING: "true"
        KC_HOSTNAME_STRICT: "false"
        KC_HOSTNAME: id.universphere.cloud
        KC_PROXY: edge
        KC_HTTP_ENABLED: "true"
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?ssl=allow
        KC_DB_USERNAME: [UNAME]
        KC_DB_PASSWORD: [PASSWORD]
        KEYCLOAK_ADMIN: [ADMIN_USER]
        KEYCLOAK_ADMIN_PASSWORD: [ADMIN_PASSWORD]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.keycloak.rule=Host(`id.universphere.cloud`)"
        - "traefik.http.routers.keycloak.entrypoints=websecure"
        - "traefik.http.routers.keycloak.tls.certresolver=myresolver"
        - "traefik.http.routers.keycloak.tls=true"
        - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
      depends_on:
        - postgres
