version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    network_mode: "host"
    volumes:
      - /home/k8s/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
