- name: create folder structure for loadbalancer
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    state: directory
    mode: '0700'
  loop:
    - "{{ nginx_volume }}"