apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging-issuer
  namespace: cert-manager
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: mis7818@thi.de
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource that will be used to store the account's private key.
      name: staging-cluster-issuer
    solvers:
      - http01:
          ingress:
            ingressClassName: traefik
