apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-tenant-api
  namespace: minio-tenant
spec:
  stripPrefix:
    prefixes:
      - /minio-generic-tenant-api

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: minio-tenant-console
  namespace: minio-tenant
spec:
  stripPrefix:
    prefixes:
      - /minio-generic-tenant-console