- name: create users
  vars:
#    ci_job_token: "{{ lookup('env', 'CI_JOB_TOKEN') }}"
    foo: "{{'value' if (my_group_var) else 'other_value'}}"
    seed: "{{ inventory_hostname }}{{ item[0].username }}"
  community.general.keycloak_user:
    auth_keycloak_url: "{{ auth_keycloak_url }}"
    auth_username: "{{ auth_username }}"
    auth_password: "{{ auth_password }}"
    auth_realm: "{{ realm }}"
    username: "{{ item[0].username }}"
    firstName: "{{ item[0].firstName }}"
    lastName: "{{ item[0].lastName }}"
    email: "{{ item[0].email }}"
    enabled: true
    emailVerified: false
    credentials:
      - type: password
        value: "{{ lookup('ansible.builtin.password', 'credentials/' + item[0].username + 'password', length=16, chars=['ascii_letters'], seed=seed) }}"
        temporary: true
    groups:
      - name: "{{ items[1] }}"
        state: present
    state: present
  loop: "{{ users | subelements('groups') }}"

- name: remove User
  community.general.keycloak_user:
    auth_keycloak_url: "{{ auth_keycloak_url }}"
    auth_username: "{{ auth_username }}"
    auth_password: "{{ auth_password }}"
    auth_realm: "{{ realm }}"
    username: "{{ item.username }}"
    state: absent
  loop: "{{ users_to_delete }}"

- name: add user to groups
  community.general.keycloak_user:
    auth_keycloak_url: "{{ auth_keycloak_url }}"
    auth_username: "{{ auth_username }}"
    auth_password: "{{ auth_password }}"
    auth_realm: "{{ realm }}"
    username: "{{ item[0].username }}"
    groups:
      - name: "{{ item[1] }}"
        state: present
    state: present
  loop: "{{ users_to_change_groups | subelements('addGroups') }}"

- name: remove user from groups
  community.general.keycloak_user:
    auth_keycloak_url: "{{ auth_keycloak_url }}"
    auth_username: "{{ auth_username }}"
    auth_password: "{{ auth_password }}"
    auth_realm: "{{ realm }}"
    username: "{{ item[0].username }}"
    groups:
      - name: "{{ item[1] }}"
        state: absent
    state: present
  loop: "{{ users_to_change_groups | subelements('removeGroups') }}"