- name: install utils
  become: true
  apt:
    name:
      - wget
      - curl
      - vim
      - git
      - tree
      - htop
      - bat
      - dnsutils
      - python3
      - net-tools
      - rsync
    update_cache: yes
    state: present