- name: Delete multiple authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: absent
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - 'keys-to-delete/*.pub'

- name: Set up multiple authorized keys
  ansible.posix.authorized_key:
    user: "{{ ansible_user }}"
    state: present
    key: "{{ lookup('file', item) }}"
  with_fileglob:
    - 'keys/*.pub'