---
# tasks file for gitlab/backup
- name: Ensure rclone is installed
  become: true
  become_user: "root"
  apt:
    name:
      - rclone
    update_cache: yes
    state: present

- name: Create a rclone config directory if it does not exist
  become: true
  become_user: "root"
  ansible.builtin.file:
    path: /root/.config/rclone/
    state: directory
    mode: '0755'

- name: Apply rclone.conf from template
  become: true
  become_user: "root"
  template:
    src: rclone.conf.j2
    dest: /root/.config/rclone/rclone.conf
    owner: root
    group: root
    mode: '0640'

- name: Apply gitlab-backup from template to cron.daily
  become: true
  become_user: "root"
  template:
    src: backup.j2
    dest: /etc/cron.daily/gitlab-backup
    owner: root
    group: root
    mode: '0755'

