- name: create groups
  community.general.keycloak_group:
    auth_keycloak_url: "{{ auth_keycloak_url }}"
    auth_username: "{{ admin_username }}"
    auth_password: "{{ admin_password }}"
    auth_realm: "{{ realm }}"
    name: "{{ item }}"
  loop: "{{ groups }}"