Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.define "debian" do |node|
    node.vm.box = "debian/bullseye64"
    node.vm.hostname = "debian"
    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "vagrant.yml"
      ansible.groups = {
            "group" => ["debian"],
            "group:vars" => {"ansible_user" => "vagrant",
            "debian_version" => "bullseye"}
          }
    end
  end
end
