---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-volume
  labels:
    type: local
spec:
  # storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/grafana"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i-k8s-node-6
                - i-k8s-node-7
                - i-k8s-node-8
                - i-k8s-node-9
                - i-k8s-node-10


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-ingester-volume
  labels:
    type: local
spec:
  # storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/loki/ingester"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i-k8s-node-6
                - i-k8s-node-7
                - i-k8s-node-8
                - i-k8s-node-9
                - i-k8s-node-10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-querier-volume
  labels:
    type: local
spec:
  # storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/loki/querier"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i-k8s-node-6
                - i-k8s-node-7
                - i-k8s-node-8
                - i-k8s-node-9
                - i-k8s-node-10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-compactor-volume
  labels:
    type: local
spec:
  # storageClassName: default
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: "/mnt/loki/compactor"
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - i-k8s-node-6
                - i-k8s-node-7
                - i-k8s-node-8
                - i-k8s-node-9
                - i-k8s-node-10
