- name: ensure GitLab volumes are present
  become: true
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
  loop:
    - "{{ gitlab_volume_config }}"
    - "{{ gitlab_volume_data }}"
    - "{{ gitlab_volume_logs }}"

- name: copy file .env
  become: true
  ansible.builtin.copy:
    src: .env
    dest: "{{ gitlab_volume }}"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'

- name: "restart: {{ restart }} and recreate: {{ recreate }} GitLab"
  community.docker.docker_container:
    name: gitlab
    image: gitlab/gitlab-ce:latest
    state: started
    restart: "{{ restart }}" # Force restart
    recreate: "{{ recreate }}" # Force recreate
    restart_policy: "always"
    labels:
      traefik.enable: "true"
      traefik.http.routers.gitlab.rule: "Host(`git.universphere.cloud`)"
      traefik.http.routers.gitlab.entrypoints: "websecure"
      traefik.http.routers.gitlab.tls.certresolver: "myresolver"
    env_file: "{{ gitlab_volume }}/.env"
    env:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://git.universphere.cloud'
        # GitLab with external proxy requires to disable auto redirect
        # https://medium.com/@gustitammam/how-to-install-self-managed-gitlab-with-nginx-reverse-proxy-and-lets-encrypt-ssl-in-ubuntu-20-04-4f7a1e87c857
        # https://janl1.de/gitlab-ce-mit-registry-und-traefik-2-0-reverse-proxy/
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        
        # DB
        gitlab_rails['db_adapter'] = "postgresql"
        gitlab_rails['db_database'] = "gitlab"
        gitlab_rails['db_username'] = "postgres"
        gitlab_rails['db_password'] = "${DATABASE_PASSWORD}"
        gitlab_rails['db_host'] = "gitlab_database"
        
        # Disable username password login
        # According to https://stackoverflow.com/questions/26618030/gitlab-disable-regular-username-password-login-and-only-allow-omniauth-login this will not work
        # In newer GitLab versions this is only possible using the admin ui in GitLab iteself
        gitlab_rails['gitlab_signin_enabled'] = false
        
        # OIDC
        gitlab_rails['omniauth_providers'] = [
                 {
                   name: "openid_connect",
                   label: "Keycloak",
                   args: {
                     name: "openid_connect",
                     scope: ["openid", "profile", "email"],
                     response_type: "code",
                     issuer: "https://keycloak.universphere.cloud",
                     client_auth_method: "query",
                     discovery: true,
                     uid_field: "preferred_username",
                     pkce: true,
                     client_options: {
                       identifier: "${OIDC_CLIENT_ID}",
                       secret: "${OIDC_CLIENT_SECRET}",
                       redirect_uri: "https://git.universphere.cloud/users/auth/openid_connect/callback",
                     }
                   }
                 }
              ]
    network_mode: bridge   
    networks:
      - name: "{{ gitlab_network }}"
    volumes:
      - "{{ gitlab_volume_config }}:/etc/gitlab"
      - "{{ gitlab_volume_data }}:/var/opt/gitlab"
      - "{{ gitlab_volume_logs }}:/var/log/gitlab"
