apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-claim
  namespace: minio-operator
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: minio-sc
  resources:
    requests:
      storage: 25Gi