apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  namespace: minio-operator
  labels: 
    type: local
spec:
  storageClassName: minio-sc
  capacity: 
    storage: 25Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minio"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
          - node
          
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume-tenant
  namespace: minio-tenant

spec:
  storageClassName: minio-sc-tenant
  capacity: 
    storage: 25Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/minio-tenant"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: # Currently on working in single-node mode and not the distributed mode
          - node2
          # - node3