apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-volume
  labels: 
    type: local
spec:
  storageClassName: minio-sc
  capacity: 
    storage: 25Gi
  accessModes: 
    - ReadWriteOnce
  hostPath:
    path: "/mnt/minio"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node2
          - node3