- name: install prerequisites
  become: true
  package:
    name:
      - ca-certificates
      - curl
      - gnupg
    update_cache: yes

- name: create /etc/apt/keyrings folder
  become: true
  ansible.builtin.file:
    path: /etc/apt/keyrings
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: add an apt signing key, uses whichever key is at the URL
  become: true
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: true

- name: add docker repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ debian_version }} stable"
    state: present
    filename: /etc/apt/sources.list.d/docker
    update_cache: yes

- name: update and upgrade packages
  become: true
  apt:
    upgrade: yes
    update_cache: yes

- name: install docker
  become: true
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    update_cache: yes

- name: restart containerd
  become: true
  service:
    name: containerd
    daemon_reload: yes
    state: restarted

- name: "Add {{ ansible_user }} user to docker group"
  become: true
  user:
    name: "{{ ansible_user }}"
    group: docker
