apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-volume-redis
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/harbor/redis"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-volume-trivy
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/harbor/trivy"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-volume-db
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/harbor/db"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-volume-registry
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 5Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/harbor/registry"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv-volume-jobservice
  labels: 
    type: local
spec:
  # storageClassName: default
  capacity: 
    storage: 1Gi
  accessModes: 
    - ReadWriteOnce
  local:
    path: "/mnt/harbor/jobservice"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - i-k8s-node-6
          - i-k8s-node-7
          - i-k8s-node-8
          - i-k8s-node-9
          - i-k8s-node-10